### ISSUE TITLE
Problema con il certificato SSL

### ISSUE THREAD

**Issue by avwarez** [fondazionebordoni/nemesys#21]
Cercando di collegarsi al server agcom con il client Ne.Me.Sys ottengo questo errore:
`May 24 00:49:37 Nemesys login.py.getActivationFile():148 [ERROR] impossibile scaricare il file di configurazione: <urlopen error [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:727)>
`
Dettagli sulla piattaforma:
```
# python --version
Python 2.7.18
```
```
# pip freeze
asn1crypto==1.3.0
backports-abc==0.5
certifi==2020.4.5.1
cffi==1.14.0
cryptography==2.4.2
enum34==1.1.10
idna==2.9
ipaddress==1.0.23
ipcalc==1.99.0
ntplib==0.3.4
prompt-toolkit==1.0.14
psutil==5.4.6
pycparser==2.20
Pygments==2.5.2
PyInquirer==1.0.3
regex==2020.5.14
singledispatch==3.4.0.3
six==1.11.0
tornado==4.5.3
wcwidth==0.1.9
xmltodict==0.11.0
```

**Comment by ewedlund** [comment]
Salve, il canale per il supporto è [helpdesk di MisuraInternet ](https://www.misurainternet.it/supporto/). Per eseguire i test tramite Nemesys l'utente dovrebbe [installare il pacchetto](https://www.misurainternet.it/download/nemesys/) adatto alla propria piattaforma (al momento sono Windows, OSX e Linux Ubuntu (alcuni altri sistemi Debian possono funzionare).
