### ISSUE TITLE
Impossibile eseguire le rilevazioni: Windows 10 64bit, errori 'GetIfTable() syscall failed'

### ISSUE THREAD

**Issue by Roamcel** [fondazionebordoni/nemesys#25]
Buongiorno.

Come da oggetto.
Scaricata l'ultima versione.
Disattivato wifi nel router
Connesso fisicamente un unico PC al router.
Appena avviata la rilevazione si presenta l'errore 
"Impossibile rilevare le schede di rete: GetIfTable() syscall failed"
Dopodichè, l'errore GetIfTable() syscall failed ogni successivo tentativo.

Il tentativo di debug da git clone su windows fallisce miserabilmente in ogni step (dai problemi con i path linux-windows ai requirement che falliscono l'installazione, al 'paver test_all' che ha problemi con pytest)

L'assistenza non risponde, e la qualità della mia linea peggiora ogni giorno.

Si chiede gentilmente supporto. Almeno un indizio su cosa causa la getiftable to fail.

Grazie

**Comment by ewedlund** [comment]
Salve, considerando il periodo di vacanze, il helpdesk potrebbe essere meno attivo. Sicuramente risponderà in tempi brevi se non lo abbia già fatto.

Per quanto riguarda l'errore, purtroppo si tratta di un problema nella libreria psutil utilizzata da Nemesys, che non riesce a recuperare i dati di una delle  interfacce di rete dal sistema. In molti casi si risolve disabilitando tutte le interfacce non utilizzate (questo lo dirà anche la risposta da helpdesk)

Per eventuali altre domande rimando a helpdesk: https://misurainternet.it/faq/17/

**Comment by Roamcel** [comment]
Grazie per il riscontro, ma i suggerimenti non hanno aiutato. Inoltre la risposta da helpdesk è stata praticamente
"deinstalla e reinstalla come amministratore".
Ho effettivamente risolto diversamente, ossia installando il programma in quattro diversi altri PC (ognuno dava un errore leggermente diverso).
Nel quarto PC, l'installazione è andata a buon fine e le rilevazioni hanno avuto luogo. Stessa rete, stesso router, stesso switch, e tutti gli altri apparecchi disconnessi e wifi spenti.
Il vero problema è nella misera capacità del software di documentare i problemi, o per meglio dire, nella mancanza assoluta di indicazioni risolutive in seguito agli errori, che lasciano gli utenti nel buio assoluto riguardo al da farsi.

Ci si aspetterebbe decisamente infinitamente di più da un programma patrocinato da una struttura ministeriale.

**Comment by ewedlund** [comment]
Come detto nel commento precedente, il problema è del recupero dei dati delle interfacce di rete del sistema: non della rete, router, switch, etc. Purtroppo Windows ne crea una quantità sproporzionata di interfacce, ed è per questo che molte volte si risolve disabilitando tutte le interfacce non utilizzate.
