### ISSUE TITLE
Run source code

### ISSUE THREAD

**Issue by daniporr** [fondazionebordoni/nemesys#36]
I understand that

> The project is not intended to be used from the code, but packaged for each platform (Mac OS, Windows and Linux). In order to use these packages, the user must register [here](https://www.misurainternet.it/).

But, if someone wants to try to run it from the source code (not to use it to get "official measurements"), how can they do that?

In your README I only see the commands to run the tests.

**Comment by ewedlund** [comment]
Hi, if you just want to run some measurements, you can take a look at this file: https://github.com/fondazionebordoni/nemesys/blob/master/common/tester.py

**Comment by daniporr** [comment]
Thank you, that works!

However, are those the same functionalities that are executed when you run the pre-built binaries?

**Comment by daniporr** [comment]
Thank you very much for your help!
